---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:stable
        ports:
        - name: web
          containerPort: 8123
          hostPort: 8123
          hostIP: <YOUR LAN INTERFACE IP HERE>
        env:
        - name: TZ
          value: America/New_York
        volumeMounts:
        - mountPath: /config/
          name: homeassistant-data
        securityContext:
          allowPrivilegeEscalation: true
      volumes:
      - name: homeassistant-data
        persistentVolumeClaim:
          claimName: homeassistant-data
