---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tftpd
  labels:
    app: tftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tftpd
  template:
    metadata:
      labels:
        app: tftpd
    spec:
#      hostNetwork: true
      containers:
      - name: tftpd
        image: wastrachan/tftpd
        ports:
        - name: tftp
          containerPort: 69
          hostPort: 69
          hostIP: <YOUR LAN IP HERE>
          protocol: UDP
        volumeMounts:
        - mountPath: /data/
          name: tftpd-data
      volumes:
      - name: tftpd-data
        hostPath:
        path: /srv/tftp/
        type: Directory
